### ISSUE TITLE
Avoid Post Cache-phase when key is already in cache

### ISSUE THREAD

**Issue by pjonsson** [ScribeMD/docker-cache#135] opened 2022-09-05 12:57 UTC
It would be nice if the post-cache phase checked that the cache key is still missing before it starts the slow operations. This will speed up workflows where runners have different run times (1 min vs 10 min), and in scenarios where some runners have a delayed start (not sure why runner starts are sometimes staggered, might be related to the load on the Github CI).

**Comment by Kurt-von-Laven** [comment] 2022-09-05 16:54
It's more manual than automatic, so I can see the value of the proposed change, but folks can pass [`read-only: false`](https://github.com/ScribeMD/docker-cache#read-only) to all but one job in such a scenario. I still think the better solution in such a situation would be to avoid concurrently performing expensive operations and to only perform them once. My understanding is that runners are allocated as they become available, which introduces some randomness to their start times.

**Comment by Kurt-von-Laven** [comment] 2022-09-05 20:18
Unfortunately, the official GitHub cache action currently makes this feature request infeasible to implement. There is [presently no exposed method for efficiently querying the cache](https://github.com/actions/toolkit/blob/bc4be505973a6a7344bfd71e1b32f77e1755310c/packages/cache/src/cache.ts). I upvoted actions/cache#321, a feature request to expose a method to test whether a key is cached without also restoring the cache, and recommend you do the same. The feature is currently on their roadmap, but there is no public timeline. Please feel free to post back here once the upstream cache action makes this request feasible.

**Comment by pjonsson** [comment] 2022-09-05 23:23
The issue you linked is closed as completed, despite only being on the roadmap. I'm surprised how they manage their backlog, it must be hard to realize that closed tickets require resources. Here's an open issue that I upvoted:
https://github.com/actions/cache/pull/420

I guess your trick from #44 might be usable in this scenario as well, the post check starts by caching a 0-byte file under a related key name, and the runner that succeeds with that also caches the docker images.

**Comment by Kurt-von-Laven** [comment] 2022-09-05 23:31
That is a pull request, but I upvoted it as well. For context, the other pertinent issue I found was closed as a duplicate of the one I linked.

Good point that [correlated caching](https://github.com/ScribeMD/docker-cache/issues/44#issuecomment-1163728664) can help here.

**Comment by Kurt-von-Laven** [comment] 2023-02-15 23:13
GitHub released [a REST API for caches](https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#list-github-actions-caches-for-a-repository) that makes this feature feasible to implement. I am not sure how valuable this feature is though since I expect the common case here would be that no job has finished saving the cache before the other jobs have all raced past the check to see whether the cache already exists.

**Comment by pjonsson** [comment] 2023-02-16 12:08
I'm not trying to bump the priority of this, but I can provide some context: with 17 jobs, it's not that hard to get into the situation where a some jobs have to wait for a runner. If the job runtimes are somewhat balanced, it's usually the late started jobs that are blocking the merge.

I don't have any experience with 5-10 jobs, so I can't comment on how common the problem is for that scenario.

**Comment by Kurt-von-Laven** [comment] 2023-02-16 12:58
I see your point. I don't know how this varies by plan, but the free plans have 20 GitHub-hosted runners, so once that limit is reached, then this optimization becomes more valuable.

**Comment by Kurt-von-Laven** [comment] 2023-11-27 07:30
[@actions/cache added a `lookupOnly` option](https://github.com/actions/toolkit/blob/%40actions/cache%403.2.2/packages/cache/src/options.ts#L63-L70) to [`restoreCache`](https://github.com/actions/toolkit/blob/%40actions/cache%403.2.2/packages/cache/src/cache.ts#L56-L72) in [v3.2.0](https://github.com/actions/toolkit/blob/%40actions/cache%403.2.2/packages/cache/RELEASES.md#320) making this feature far easier to implement in JavaScript than it previously was through the REST API.

**Closed** 2024-03-13 03:18 UTC
Labels: good first issue, performance
